# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Leonardo Urbano'
tagline:          'Data Scientist'
description:      'To add'
url:              http://urbanoleonardo.github.io
baseurl:          /

author:
  name:           'Leonardo Urbano'
  url:            https://github.com/urbanoleonardo/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/urbanoleonardo/urbanoleonardo.github.io
  main:           https://github.com/urbanoleonardo/
